[versions]
accompanistPermissions = "0.37.3"
accompanistPermissionsVersion = "0.35.0-alpha"
activityComposeVersion = "1.8.0"
agp = "8.13.1"
androidxMaterial3 = "1.4.0"
androidxNavigationCompose = "2.8.0"
googlePlayServicesMaps = "18.2.0"
kotlin = "2.2.20"
coreKtx = "1.17.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
lifecycleRuntimeKtx = "2.9.4"
activityCompose = "1.11.0"
composeBom = "2025.10.00"
lifecycleViewmodelCompose = "2.9.4"
mapsCompose = "6.12.1"
mapsComposeVersion = "6.12.1"
material3 = "1.3.0"
materialIconsExtended = "1.7.8"
materialIconsExtendedVersion = "1.5.4"
navigationCompose = "2.9.5"
playServicesLocationVersion = "21.3.0"
playServicesMaps = "19.2.0"
roomKtxVersion = "2.6.1"
ui = "1.9.3"
material3Version = "1.4.0"
playServicesLocation = "21.3.0"
foundation = "1.9.3"
compose = "1.9.3"
navigationComposeVersion = "2.9.5"
playServicesMapsVersion = "19.2.0"
roomCommonJvm = "2.8.3"
roomRuntimeJvm = "2.8.3"
roomKtx = "2.8.3"
uiTestManifest = "1.9.4"
foundationLayout = "1.9.4"
composeMaterial = "1.5.5"


[libraries]
accompanist-permissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "accompanistPermissions" }
accompanist-permissions-v0350alpha = { module = "com.google.accompanist:accompanist-permissions", version.ref = "accompanistPermissionsVersion" }
androidx-activity-compose-v180 = { module = "androidx.activity:activity-compose", version.ref = "activityComposeVersion" }
androidx-compose-material-icons-extended-v154 = { module = "androidx.compose.material:material-icons-extended", version.ref = "materialIconsExtendedVersion" }
androidx-compose-ui-text = { module = "androidx.compose.ui:ui-text", version.ref = "uiTestManifest" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycleRuntimeKtx" }
androidx-material3 = { module = "androidx.compose.material3:material3", version.ref = "androidxMaterial3" }
androidx-navigation-compose-v280 = { module = "androidx.navigation:navigation-compose", version.ref = "androidxNavigationCompose" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "roomKtxVersion" }
androidx-room-ktx-v261 = { module = "androidx.room:room-ktx", version.ref = "roomKtxVersion" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "roomKtxVersion" }
androidx-ui = { module = "androidx.compose.ui:ui", version.ref = "uiTestManifest" }
androidx-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "uiTestManifest" }
androidx-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "uiTestManifest" }
androidx-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "uiTestManifest" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-compose-material = { module = "androidx.compose.material:material", version.ref = 'compose'}
androidx-compose-material-icons-extended = { module = "androidx.compose.material:material-icons-extended", version.ref = "materialIconsExtended" }

# Otras librer√≠as de Compose que necesites
androidx-compose-foundation = { module = "androidx.compose.foundation:foundation" }
androidx-compose-runtime = { module = "androidx.compose.runtime:runtime" }
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigationComposeVersion" }
maps-compose = { module = "com.google.maps.android:maps-compose", version.ref = "mapsComposeVersion" }
play-services-location = { module = "com.google.android.gms:play-services-location", version.ref = "playServicesLocationVersion" }
play-services-maps = { group = "com.google.android.gms", name = "play-services-maps", version.ref = "playServicesMapsVersion" }
androidx-room-common-jvm = { group = "androidx.room", name = "room-common-jvm", version.ref = "roomCommonJvm" }
androidx-room-runtime-jvm = { group = "androidx.room", name = "room-runtime-jvm", version.ref = "roomRuntimeJvm" }
androidx-room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "roomKtx" }
play-services-maps-v1820 = { module = "com.google.android.gms:play-services-maps", version.ref = "googlePlayServicesMaps" }
androidx-compose-foundation-layout = { group = "androidx.compose.foundation", name = "foundation-layout", version.ref = "foundationLayout" }
compose-material = { group = "androidx.wear.compose", name = "compose-material", version.ref = "composeMaterial" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
[bundles]
compose = ["androidx-compose-ui", "androidx-compose-ui-graphics", "androidx-compose-ui-tooling-preview", "androidx-compose-material3", "androidx-compose-material"]